// <auto-generated />
using System;
using ExercicioEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExercicioEF.Migrations
{
    [DbContext(typeof(ExercicioEFDbContext))]
    [Migration("20210920192611_AddTable_User_Cargo_Constraint")]
    partial class AddTable_User_Cargo_Constraint
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExercicioEF.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CARGO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoCargo")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("DESC_CARGO");

                    b.HasKey("Id");

                    b.ToTable("TB_CARGO");
                });

            modelBuilder.Entity("ExercicioEF.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USER")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasColumnType("VARCHAR(11)")
                        .HasColumnName("DS_CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_NASC");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("NM_USER");

                    b.HasKey("Id");

                    b.ToTable("TB_USER");
                });

            modelBuilder.Entity("ExercicioEF.Models.User_Cargo", b =>
                {
                    b.Property<int>("Id_User_Cargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USER_CARGO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Cargo")
                        .HasColumnType("int")
                        .HasColumnName("ID_CARGO");

                    b.Property<int>("Id_User")
                        .HasColumnType("int")
                        .HasColumnName("ID_USER");

                    b.HasKey("Id_User_Cargo");

                    b.HasIndex("Id_Cargo");

                    b.HasIndex("Id_User");

                    b.ToTable("TB_USER_CARGO");
                });

            modelBuilder.Entity("ExercicioEF.Models.User_Cargo", b =>
                {
                    b.HasOne("ExercicioEF.Models.Cargo", "Cargo")
                        .WithMany("User_Cargo")
                        .HasForeignKey("Id_Cargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExercicioEF.Models.User", "User")
                        .WithMany("UserCargo")
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExercicioEF.Models.Cargo", b =>
                {
                    b.Navigation("User_Cargo");
                });

            modelBuilder.Entity("ExercicioEF.Models.User", b =>
                {
                    b.Navigation("UserCargo");
                });
#pragma warning restore 612, 618
        }
    }
}
